# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.0
  - 1.3
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
  - arm64
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  exclude:
    - arch: x86
      os: osx
    - arch: arm64
      os: osx
    - arch: arm64
      os: windows
    - arch: arm64
      julia: nightly
  include:
    - stage: Documentation
      julia: 1.0
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          Pkg.build()
          include("docs/make.jl")'
      after_success: skip
